### ISSUE TITLE
Add component tree display

### ISSUE THREAD

**Issue by phillipskevin** [canjs/devtools#15]
Like the elements panel, but only show components.

## Issues
- [x] [Add "name" data to `getViewModelData` response](https://github.com/canjs/devtools/issues/37)
- [x] [Display "name" data in ViewModelEditor](https://github.com/canjs/can-devtools-components/issues/41)

- [x] [Generate Component Tree data](https://github.com/canjs/devtools/issues/38)
- [x] [Create Component Tree component](https://github.com/canjs/can-devtools-components/issues/42)
- [x] [Create Dropdowns component](https://github.com/canjs/can-devtools-components/issues/43)
- [x] [Create CanJS Panel Component](https://github.com/canjs/can-devtools-components/issues/45)
- [x] [Add functions for adding and deleting breakpoints](https://github.com/canjs/devtools/issues/39)
- [x] [Create Breakpoints component](https://github.com/canjs/can-devtools-components/issues/44)

**Comment by phillipskevin** [comment]
Here is a (very rough) idea for what I think the first version of this should look like:

<img width="1441" alt="canjs-panel" src="https://user-images.githubusercontent.com/5851984/48110045-995a0300-e20f-11e8-9c68-34022d9a2747.png">

The left side will show the Component Tree. This will show any elements that have a ViewModel (possibly also elements with attribute bindings?). You can use the input at the top to filter the Components.

The right side will have a few tabs:
* ViewModel Editor (same as we have now in the Elements Panel)
* Bindings Graph (same)
* Log - This will show a log of all changes to the current ViewModel (as well as any "change" breakpoints)

I'll add some more details as I continue working on the prototype for this.

cc @justinbmeyer @matthewp @ryangwilson

**Comment by phillipskevin** [comment]
Here is some interaction of the ViewModel Editor:

![viewmodel-editor-tab](https://user-images.githubusercontent.com/5851984/48110259-af1bf800-e210-11e8-8af2-a3370eadb440.gif)

It works basically the same way as the current devtools "sidebar", except that you select components in the Tree View.

If you make a change to the ViewModel that causes elements to be added/removed, the Component Tree will update automatically.

By default when you open the CanJS Panel, the element selected in the Elements Panel will be selected in the ViewModel Editor.

**Comment by justinbmeyer** [comment]
We will store all changes to all ViewModels?

What about logStack?

**Comment by phillipskevin** [comment]
Here is what I'm thinking for the Log tab:

![change-log](https://user-images.githubusercontent.com/5851984/48111852-25bcf380-e219-11e8-984b-dad4241b85ea.gif)

I think we show the changes to the ViewModel of the selected component (maybe capped at the last 50 changes or something).

We also provide a way to easily create breakpoints as mentioned in https://github.com/canjs/can-devtools-components/issues/9#issuecomment-399134338. The breakpoint would automatically print the logstack.

We could also allow the user to expand each change to see the logstack, but I think this is something we add after the MVP.

**Comment by phillipskevin** [comment]
Here is a prototype for a simplified version of the CanJS panel, which just includes the Component Tree View on the left and the ViewModel Editor and a dropdown for "break on change" breakpoints on the right:

![breakpoints-dropdown](https://user-images.githubusercontent.com/5851984/48858308-9e2ac500-ed80-11e8-84bb-90082facab4e.gif)

**Comment by phillipskevin** [comment]
Yeah, I think that's good. We can add the "dropdown" piece for the ViewModel Editor also and style it more like the built-in Chrome devtools sidebar.

**Comment by phillipskevin** [comment]
We'll need to style this more like the native devtools, but here are some images to give a general idea.

Default view:

![image](https://user-images.githubusercontent.com/5851984/49172198-fecc7b80-f305-11e8-8751-db5029b89c22.png)

Everything expanded:

![image](https://user-images.githubusercontent.com/5851984/49172211-0724b680-f306-11e8-936d-8b7b5673e68d.png)
